# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
# Copyright (c) 2024 Bo Lu, Leah Bercovith
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 80
    url: https://geocore-pygeoapi-dev.api.geo.ca/
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
        - fr-CA
    # cors: true
    pretty_print: true
    limit: 10
    templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
      base: _base_geoca.html
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution:
            en: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'
            fr: '<a href="https://www.openstreetmap.org/copyright">© Contributeurs d&apos;OpenStreetMap</a>'
#    manager:
#        name: TinyDB
#        connection: /tmp/pygeoapi-process-manager.db
#        output_dir: /tmp/
    # ogc_schemas_location: /opt/schemas.opengis.net
    
logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: OGC API - Records for geo.ca
            fr: OGC API - Records pour geo.ca
        description:
            en: An OGC API - Records compliant website for the Canadian Geospatial Platform (CGP). The application is based on the pygeoapi core version provided in the footer. This service has been augmented with a 'geocore' provider  to connect with the geo.ca backend
            fr: Un site Web conforme à l'API OGC - Records pour la Plateforme géospatiale canadienne (CGP). L'application est basée sur la version principale de pygeoapi fournie dans le pied de page. Ce service a été complété par un fournisseur « geocore » pour se connecter au backend geo.ca.
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service:
            en: https://geo.ca/terms-and-conditions/
            fr: https://geo.ca/fr/avis/
        url:
            en: https://canadian-geospatial-platform.github.io/geocore/
            fr: https://canadian-geospatial-platform.github.io/geocore/
    license:
        name: 
            en: Open Government Licence - Canada 
            fr: Licence du gouvernement ouvert – Canada 
        url: 
            en: https://open.canada.ca/en/open-government-licence-canada
            fr: https://ouvert.canada.ca/fr/licence-du-gouvernement-ouvert-canada
    provider:
        name: 
            en: Canadian Geospatial Platform (CGP)
            fr: Plateforme Géospatiale Canadienne (PGC)
        url:
            en: https://geo.ca/home/
            fr: https://geo.ca/fr/accueil/
    contact:
        name: Lastname, Firstname
        position: Position Title
        address:
            en: 580 Booth Street
            fr: 580, rue Booth
        city: Ottawa
        stateorprovince: Ontario
        postalcode: K1A 0E4
        country: Canada
        phone:
            en: None
            fr: Aucun
        fax:
            en: None
            fr: Aucun
        email: geo@nrcan-rncan.gc.ca
        url: Contact URL
        instructions: geo@nrcan-rncan.gc.ca
        role: pointOfContact

resources:
    canadian-geospatial-platform:
        type: collection
        title: 
            en: Canadian Geospatial Platform (CGP) metadata
            fr: Métadonnées de la Plateforme géospatiale canadienne (PGC)
        description: 
            en: Canadian Geospatial Platform metadata (GeoCore API provider)
            fr: Métadonnées de la Plateforme géospatiale canadienne (fournisseur d'API GeoCore)
        keywords:
            en:
                - canada
                - geocore
                - nrcan
                - fgp
                - cgp
            fr:
                - canada
                - geocore
                - rncan
                - pgf
                - pgc
        links:
            -   type: text/html
                rel: canonical
                title: information
                href: https://geocore.api.geo.ca/id/v2?id=ccmeo-hrdem-lidar-MB-Shoal_Lakes_2019-1m&lang=en
                hreflang: en-CA
        extents:
            spatial:
                bbox: [ -140.99778,41.6751050889,-52.6480987209,83.23324 ]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            -   type: record
                name: GeoCore
                data:
                    base_url: https://hqdatl0f6d.execute-api.ca-central-1.amazonaws.com/dev
                    mapping:
                        # Maps provider function calls to specific endpoints
                        query: geo
                        get: id
                    queryables:
                        # geoCore does not offer a way to retrieve the queryables: define them here
                        theme:
                            label-en: Themes
                            label-fr: Thèmes
                            type: string
                            values-en:
                                - administration
                                - economy
                                - environment
                                - imagery
                                - infrastructure
                                - science
                                - society
                                - legal
                                - emergency
                            values-fr:
                                - administration
                                - économie
                                - environnement
                                - imagerie
                                - infrastructure
                                - renseignements juridiques
                                - science
                                - société
                                - urgences
                        type:
                            label-en: Types
                            label-fr: Types
                            type: string
                            values-en:
                                - API
                                - Application
                                - Collection
                                - Community
                                - Dataset
                                - Service
                            values-fr:
                                - API
                                - Application
                                - Collection
                                - Communauté
                                - Jeu de données
                                - Service
                        org:
                            label-en: Organizations
                            label-fr: Organisations
                            type: string
                            values-en:
                                - Agriculture and Agri-Food Canada
                                - Canadian Geospatial Data Infrastructure Web Harvester
                                - Canadian Heritage
                                - Canadian Northern Economic Development Agency
                                - Canadian Nuclear Safety Commission
                                - Canadian Space Agency
                                - Department of Justice
                                - Elections Canada
                                - Employment and Social Development Canada
                                - Environment and Climate Change Canada
                                - Fisheries and Oceans Canada
                                - Government and Municipalities of Québec
                                - Government of Alberta
                                - Government of British Columbia
                                - Government of Manitoba
                                - Government of New Brunswick
                                - Government of Newfoundland and Labrador
                                - Government of Northwest Territories
                                - Government of Nova Scotia
                                - Government of Nunavut
                                - Government of Ontario
                                - Government of Prince Edward Island
                                - Government of Saskatchewan
                                - Government of Yukon
                                - Impact Assessment Agency of Canada
                                - Indigenous Services Canada
                                - Innovation, Science and Economic Development Canada
                                - Natural Resources Canada
                                - Parks Canada
                                - Public Health Agency of Canada
                                - Statistics Canada
                                - Transport Canada
                            values-fr:
                                - Agence Canadienne de Développement économique du Nord
                                - Agence d'évaluation d'impact du Canada
                                - Agence de la santé publique du Canada
                                - Agence spatiale canadienne
                                - Agriculture et Agroalimentaire Canada
                                - Commission canadienne de sûreté nucléaire
                                - Défense nationale
                                - Élections Canada
                                - Emploi et Développement social Canada
                                - Environnement et Changement climatique Canada
                                - Gouvernement de l'Alberta
                                - Gouvernement de l'Île-du-Prince-Édouard
                                - Gouvernement de l'Ontario
                                - Gouvernement de la Colombie-Britannique
                                - Gouvernement de la Nouvelle-Écosse
                                - Gouvernement de la Saskatchewan
                                - Gouvernement de Terre-Neuve-et-Labrador
                                - Gouvernement des Territoires du Nord-Ouest
                                - Gouvernement du Manitoba
                                - Gouvernement du Nouveau-Brunswick
                                - Gouvernement du Nunavut
                                - Gouvernement du Yukon
                                - Gouvernement et municipalités du Québec
                                - Ministère de la Justice
                                - Moissonneur web de l'Infrastructure canadienne de données géospatiales
                                - Parcs Canada
                                - Patrimoine canadien
                                - Pêches et Océans Canada
                                - Ressources naturelles Canada
                                - Services aux Autochtones Canada
                                - Statistique Canada
                                - Transports Canada
                id_field: externalId
                time_field: record-created
                title_field: title
                languages:
                    - en-CA
                    - fr-CA
